### ISSUE TITLE
Can I exclude compressed files from TVirtualExplorerTreeview?

### ISSUE THREAD

**Issue by luebbe** [pyscripter/MustangpeakVirtualShellTools#15]
The goal is that just folders and no compressed files inside a folder should be shown in the Treeview.
I've been playing around with the fileobjects property, but haven't found a way to exclude compressed files.

**Comment by pyscripter** [comment]
You can apply  filters.  Have a look at the PyScripter File Explorer (frmFileExplorer).  Out of the top of my head you can use the file extension to filter out files, but I believe there is a better way.

**Comment by luebbe** [comment]
Thanks for the pointer, but still calling for help ;)

I'm getting closer. The goal is to create a stylable browse for folder dialog that doesn't contain any files. I can filter by file extension in TreeEnumFolder like this:

```
procedure TFolderDialog.vstExplorerTreeEnumFolder(
  Sender: TCustomVirtualExplorerTree;
  Namespace: TNamespace;
  var AllowAsChild: Boolean);
begin
  inherited;
  if Length(FFileExtFilter) > 0 then
    AllowAsChild := not MatchText(NameSpace.Extension, FFileExtFilter);
end;

```

This will reliably remove '.zip' files and whatever else I add to the FFileExtFilter array from the tree. But the '+' expansion mark is still shown in the VirtualExplorerTree for a folder that contains only '.zip' files and no subfolders. It looks like there are still 'invisible' children.

See attached screenshot: The Gateway and Motor folders contain only .zip files and should not have the '+'. The Getriebe folder contains subfolders. The '+' is ok in this case.

![2018_04_17_10_34_07_search_folder](https://user-images.githubusercontent.com/3872576/38858211-6258afe8-422b-11e8-8c4f-8acd402ee8e1.png)

**Comment by pyscripter** [comment]
There is also the toBrowseExecuteZipFolder property of VirtualExplorer.  It only applied to zip files but I have just  changed it to apply to all compressed folders.

**Comment by pyscripter** [comment]
Such a function would be useful and I could add it to MustangpeakVirtualShellTools.  Have a look at MustangpeakVirtualShellTools in MPCommon Utilities about a possible interface to such function.

**Comment by pyscripter** [comment]
I did some research to see whether there is a good way to check whether a file is a compressed archive but could not find any  apart from using the file extension.
