### ISSUE TITLE
BrowseTo(APath) fails when a part of the path is "hidden"

### ISSUE THREAD

**Issue by luebbe** [pyscripter/MustangpeakVirtualShellTools#16]
When APath poits to a folder in AppData, e.g. APath := 'C:\Users\<user>\AppData\Local\...';

`TCustomVirtualExplorerTree.BrowseTo(APath)` doesn't navigate to this folder.

I traced into` TCustomVirtualExplorerTree.WalkPIDLToNode` and saw that the `while (Root <> nil) and not Done` do loop never reaches the `Done = true` state.

I also tried combining a TVirtualExplorerCombobox with a TVirtualExplorerTreeview. In the combobox I can

- enter %appdata%, which is expanded correctly in the combobox 
- select any path inside appdata from the combobox

but the treeview never navigates there. How can I solve this problem?

**Comment by pyscripter** [comment]
Have you tried to include foHidden in the FileObjects property?  For the Combobox is in by default but not for the Tree.

**Comment by luebbe** [comment]
Can you believe that I searched for an option like this and didn't find it...
Thanks, that was the important hint. I didn't see a FileObjects property in the Combobox though.

**Comment by pyscripter** [comment]
You can set it through the property of TVirtualExplorerCombobox  named PopupExplorerDropDown or possibly PopupExplorerTree.

**Comment by luebbe** [comment]
The confusing thing about this behavior is that in Windows explorer you can paste a path like 'C:\Users<user>\AppData\Local' and the explorer navigates there even when hidden objects are hidden.
The VirtualExplorerExplorerTree acts different here. It either fails, when foHidden is not set or it works *and* shows the hidden nodes.
