### ISSUE TITLE
VET's rows squezed together in run-time

### ISSUE THREAD

**Issue by adem0x** [pyscripter/MustangpeakVirtualShellTools#21]
I don't know how much of this is directly attributable to VET, but (see picture below) when I run the Demos, what looks perfectly good in design time turns out to be almost unusable in run time. Rows are squeezed together.

![Capture1](https://user-images.githubusercontent.com/1360723/54468784-64ebea00-47a1-11e9-942f-65fecd0e6d97.JPG)

![Capture2](https://user-images.githubusercontent.com/1360723/54468787-674e4400-47a1-11e9-8278-c4c86b689825.JPG)

By the way, I have made sure the Form's Scaled property is True.

Is there any other setting/properties to alter?

**Comment by pyscripter** [comment]
You are probably using a high DPI monitor and you manifest declares your application as DPI aware (Per Monitor2 or something).

You need to set the Option toAutoChangeScale to True..  It is under AutoOptions.  This is by default set for new trees, but the demos have not been updated.  You are welcome to submit a PR correcting this.
