### ISSUE TITLE
Is MustangpeakVirtualShellTools outdated?

### ISSUE THREAD

**Issue by groehner** [pyscripter/MustangpeakVirtualShellTools#23]
[dcc32 Error] ColumnFormSpTBX.pas(177): E2250 There is no overloaded version of 'MoveTo' that can be called with these arguments
	undeclared identifier amInsertAfter 
solvable by adding VirtualTrees.Types to the uses-clause.

[dcc32 Error] VirtualExplorerTree.pas(11996): E2035 Not enough actual parameters
procedure TCustomVirtualExplorerCombobox.PaintCombo(PaintDC: HDC);
      if SkinManager.GetSkinType in [sknSkin,sknDelphiStyle] then

GetSkinType needs Parameter
	  function GetSkinType(AControl: TControl): TSpTBXSkinType;

[dcc32 Error] VirtualExplorerTree.pas(12004): E2010 Incompatible types: 'TControl' and 'TCanvas'
       SpDrawXPComboButton(ACanvas, ComboButtonR, Enabled, IsHotTracked,
         IsHotTracked, PopupExplorerDropDown.Visible, not UseRightToLeftReading);

procedure SpDrawXPComboButton(AControl: TControl; ACanvas: TCanvas; ARect: TRect; Enabled, FrameHotTrack,
  HotTrack, DroppedDown, RightAligned: Boolean;  DPI: Integer);

**Comment by pyscripter** [comment]
SpTBX support, which was incomple anyway, is no longer maintained and will be removed in the future.   Vcl styles is used for skinning instead and SpTBX also supports Vcl.Styles.

On the other hand TBX is still supported.
