### ISSUE TITLE
Empty list when change root dir on context menu

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/MustangpeakVirtualShellTools#9]
```
What steps will reproduce the problem?
1. Right click to show context menu
2. Click Up

The window is empty.

```

Original issue reported on code.google.com by `UserId...@gmail.com` on 3 Nov 2013 at 2:35

Attachments:
- [Projects.zip](https://storage.googleapis.com/google-code-attachments/mustangpeakvirtualshelltools/issue-9/comment-0/Projects.zip)

**Comment by pyscripter** [comment]
In a recent version of Delphi you can do this:
```
procedure TForm1.mniUpClick(Sender: TObject);
var
  Path: string;
begin
  TThread.ForceQueue(nil, procedure
  begin
    Path := ExtractFileDir(ExplorerList.RootFolderNamespace.NameForParsing);
    ExplorerList.BrowseTo(Path);
  end);
end;
```
On older versions create a custom message write a message handle and in TForm1.mniUpClick(Sender: TObject); post the message you created with PostMessage.  Or you can handle the same with a timer.
